### PR TITLE
Docs: Update instructions for local deployment to use aiidalab-launch.

### PR DESCRIPTION
**Pull request by csadorf**

### CODE REVIEW

**Review by yakutovicha — APPROVED** [review]
LGTM!

**Comment by csadorf** [comment]
Ok, then let's merge this. Maybe in a future update we can make the "get started" paths a bit more akin as to how we present them in the AiiDA (core) docs. With panels and so on.

**Comment by csadorf** [comment]
@ltalirz I primarily wanted to make you aware of this. Feel free to review after merge, we can still address any comments then.

**Comment by ltalirz** [comment]
> @ltalirz I primarily wanted to make you aware of this. Feel free to review after merge, we can still address any comments then.

Thanks @csadorf , I had a quick look and it looked good to me as well. Will open issues/PRs in case I encounter things that could be improved.

**Pull request merged**
