### PR TITLE
Revise the determination of available remote versions.

### LINKED ISSUE #145: App update is not working.
I realised that apps update on the AiiDalab is broken.

I just released a new version of the aiidalab-empa-nanoribbons app (`1.1.2`). The update was successfully detected by the app:

Screenshot 2021-01-14 at 17 02 33

When I clicked on the update button I got the following error:

```python

---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/ipywidgets/widgets/widget_selection.py in findvalue(array, value, compare)
    136     try:
--> 137         return next(x for x in array if compare(x, value))
    138     except StopIteration:

StopIteration: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/ipywidgets/widgets/widget_selection.py in _validate_value(self, proposal)
    240         try:
--> 241             return findvalue(self._options_values, value, self.equals) if value is not None else None
    242         except ValueError:

/opt/conda/lib/python3.7/site-packages/ipywidgets/widgets/widget_selection.py in findvalue(array, value, compare)
    138     except StopIteration:
--> 139         raise ValueError('%r not in array'%value)
    140 

ValueError: 'git:refs/tags/v1.1.2' not in array

During handling of the above exception, another exception occurred:

TraitError                                Traceback (most recent call last)
/opt/aiidalab-home/home/app_manager.py in _update_app(self, _)
    279             self._show_msg_failure(str(error))
    280         else:
--> 281             self.version_selector.version_to_install.value = version
    282             self._show_msg_success("Updated app.")
    283 

/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in __set__(self, obj, value)
    602             raise TraitError('The "%s" trait is read-only.' % self.name)
    603         else:
--> 604             self.set(obj, value)
    605 
    606     def _validate(self, obj, value):

/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in set(self, obj, value)
    576 
    577     def set(self, obj, value):
--> 578         new_value = self._validate(obj, value)
    579         try:
    580             old_value = obj._trait_values[self.name]

/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in _validate(self, obj, value)
    610             value = self.validate(obj, value)
    611         if obj._cross_validation_lock is False:
--> 612             value = self._cross_validate(obj, value)
    613         return value
    614 

/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in _cross_validate(self, obj, value)
    616         if self.name in obj._trait_validators:
    617             proposal = Bunch({'trait': self, 'value': value, 'owner': obj})
--> 618             value = obj._trait_validators[self.name](obj, proposal)
    619         elif hasattr(obj, '_%s_validate' % self.name):
    620             meth_name = '_%s_validate' % self.name

/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in __call__(self, *args, **kwargs)
    973         """Pass `*args` and `**kwargs` to the handler's function if it exists."""
    974         if hasattr(self, 'func'):
--> 975             return self.func(*args, **kwargs)
    976         else:
    977             return self._init_call(*args, **kwargs)

/opt/conda/lib/python3.7/site-packages/ipywidgets/widgets/widget_selection.py in _validate_value(self, proposal)
    241             return findvalue(self._options_values, value, self.equals) if value is not None else None
    242         except ValueError:
--> 243             raise TraitError('Invalid selection: value not found')
    244 
    245     @observe('value')

TraitError: Invalid selection: value not found
```

@csadorf can you please have a look?

P.S. The update did happen, though. When I reload the page I see the updated version of the app:

Screenshot 2021-01-14 at 17 07 12

### PR DESCRIPTION
**Pull request by csadorf**
This change set fixes #145 and slightly changes the app management interface for apps that are not installed. Namely, only one version is shown to be available for installation (corresponding to the release line). That is because with the current setup of the registry data it is impossible to determine which tags actually correspond to the release line, all we can say is whether the commit sha of the release line corresponds to a given tag.

This means that the available version shown is either a tag corresponding to the release line, the branch name (if there is no tag), or simply the SHA in all other cases.

As a side note, we should consider moving some (or most) of the release line logic into the registry compilation, where we have more data available. That would make it easier to compile available versions within the runtime environment. The determination of compatibility would still need to occur in the runtime environment.

### CODE REVIEW

**Review by yakutovicha — COMMENTED** [review]
I am afraid the issue remains. I installed `aiidalab` with your changes and tried to update a package. The issue I got was exactly the same.

If this helps, I can give a tarball that contains an app to be updated.

**Comment by csadorf** [comment]
> I am afraid the issue remains. I installed `aiidalab` with your changes and tried to update a package. The issue I got was exactly the same.
> 
> If this helps, I can give a tarball that contains an app to be updated.

I'm almost certain that you did not actually use the correct aiidalab package, but please send me the tarball and I will test it myself.

**Comment by yakutovicha** [comment]
I hope I did a mistake. Here is the file: [aiidalab-widgets-base.tar.gz](https://github.com/aiidalab/aiidalab/files/5917678/aiidalab-widgets-base.tar.gz)

**Comment by csadorf** [comment]
> I hope I did a mistake. Here is the file: [aiidalab-widgets-base.tar.gz](https://github.com/aiidalab/aiidalab/files/5917678/aiidalab-widgets-base.tar.gz)

I can confirm that the bug is indeed still present. Looks like I had some trouble reproducing it with the app state I was working with. Working on a fix right now.

**Comment by csadorf** [comment]
Closing this in lieu of https://github.com/aiidalab/aiidalab-home/pull/55 .

**Pull request closed without merging**
