### PR TITLE
Revise installation and update implementation

### PR DESCRIPTION
**Pull request by csadorf**
This change set revises how the app installation, update determination, and app update flow is implemented and thus fixes issues #86 and #87. The change set also includes corresponding integration tests of these flows in various scenarios.

### CODE REVIEW

**Comment by yakutovicha** [comment]
testing it.

**Comment by yakutovicha** [comment]
If the app is not in the registry, does it suppose to have the "Latest Version": 
Screenshot 2020-09-03 at 10 45 55

**Comment by csadorf** [comment]
> If the app is not in the registry, does it suppose to have the "Latest Version"?

No, I think it should say that it is not possible to determine whether it is latest version. I'll fix that.

**Review by yakutovicha — COMMENTED** [review]
Another thing. I created a new branch starting from `master`. I didn't modify the new branch at all.

What I see is: the fact that it might be another branch is correctly recognized, while I cannot click on the `Install` button to bring things to the master branch.

Screenshot 2020-09-03 at 11 01 33

**Comment by csadorf** [comment]
> Another thing. I created a new branch starting from `master`. I didn't modify the new branch at all.

I assume you meant to imply that you also checked out that other branch. The behavior is then as expected. Once a user leaves the "release line" by either checking out a different branch, or a commit which neither tagged on the branch or is the head commit, the UI capabilities are greatly reduced. The app is assumed to be in "developer" mode at that point, because it should be impossible to reach that state without manually manipulating the app state on the terminal.

**Comment by yakutovicha** [comment]
> I assume you meant to imply that you also checked out that other branch.

right. 

>  The behavior is then as expected. Once a user leaves the "release line" by either checking out a different branch, or a commit which is neither tagged on the branch nor the branch's head commit, the UI capabilities are greatly reduced. 

I think users should be able to come back to the standard release line, no?

**Comment by yakutovicha** [comment]
For some reason, I don't see the updates for the `aiidalab-widgets-base` package. The version `1.0.0b10` has been released a few days ago:

Screenshot 2020-09-03 at 12 08 33

**Comment by yakutovicha** [comment]
I pulled the newest changes

For some reason, when I updated aiidalab-widgets-base to `1.0.0b9` version, I got back:

Screenshot 2020-09-03 at 12 13 07

**Comment by CasperWA** [comment]
> > The behavior is then as expected. Once a user leaves the "release line" by either checking out a different branch, or a commit which is neither tagged on the branch nor the branch's head commit, the UI capabilities are greatly reduced.
> 
> I think users should be able to come back to the standard release line, no?

Well we could consider a "reset" button that only exists when the checkbox has been checked.
But otherwise I agree with @csadorf's conclusion here. If you as the user broke it, it's your responsibility to fix it. But a "reset to default/factory settings", might be an idea.

**Comment by csadorf** [comment]
> For some reason, I don't see the updates for the `aiidalab-widgets-base` package. The version `1.0.0b10` has been released a few days ago:

The specific version (`1.0.0b10`) does not show up, because there is no way to figure out what versions are available without fetching the remote ref. That said, even if I reset my repository to not know about the upstream commit, the update button is enabled and it is indicated that there are updates available, and when I manually fetch, the version shows up, even if not installed. So I am not able to reproduce the issue on my end.

The *updates available* indication (via the label and the button) is enabled when one of the following two conditions is met:
1. Our local branch reference is out-of-date (as determined by comparing with the registry) and we need to fetch.
2. The installed version is not the latest on the specified release line (only possible for branches).

**Comment by csadorf** [comment]
> > > The behavior is then as expected. Once a user leaves the "release line" by either checking out a different branch, or a commit which is neither tagged on the branch nor the branch's head commit, the UI capabilities are greatly reduced.
> > 
> > 
> > I think users should be able to come back to the standard release line, no?
> 
> Well we could consider a "reset" button that only exists when the checkbox has been checked.
> But otherwise I agree with @csadorf's conclusion here. If you as the user broke it, it's your responsibility to fix it. But a "reset to default/factory settings", might be an idea.

We can consider that, but that would not be in line with what we had agreed upon previously, and would anyways need to be implemented in the home app, so I suggest that we postpone that.

**Comment by csadorf** [comment]
> I pulled the newest changes
> 
> For some reason, when I updated aiidalab-widgets-base to `1.0.0b9` version, I got back:
> 
> Screenshot 2020-09-03 at 12 13 07

Are you sure that your local copy of the app is pointing to the correct remote and is not otherwise modified? I am not able to reproduce the issue on my end.

**Comment by yakutovicha** [comment]
> The specific version (`1.0.0b10`) does not show up, because there is no way to figure out what versions are available without fetching the remote ref.

The Git-related information is fetched automatically hourly, so you can find all the available tags there: https://aiidalab.materialscloud.org/appsdata/apps_meta.json

**Comment by csadorf** [comment]
> > Edit: Btw, as a work-around until then, a simple reset should be to just uninstall and reinstall the app. :)
> 
> So we could, essentially, have a button that does this all-in-one?

Yes.

**Comment by csadorf** [comment]
@yakutovicha This should be all set.

**Comment by yakutovicha** [comment]
> @yakutovicha This should be all set.

I do a quick test and then will approuve

**Review by yakutovicha — APPROVED** [review]
Looks good, thanks @csadorf!

**Pull request merged**
