### PR TITLE
Pre-commit update + fix docs build

### PR DESCRIPTION
**Pull request by danielhollas**
Update of mypy now detects some new issues. Not sure if these are real or a mypy bug, need to investigate more.

EDIT: Looks like mypy was right and we were not ensuring that we return a proper types in one of the functions. The refactor I made is not very pretty but does the trick. Further cleanup would be more work I think.

### CODE REVIEW

**Comment by unkcpz** [comment]
For the doc build failure, I guess https://github.com/aiidateam/aiida-core/pull/6253 this will help? Or maybe just simply update the sphinx version to the latest.

**Comment by danielhollas** [comment]
I've managed to fix the docs build in the end (in an ugly way). LMK if you want me to split it to a separate PR.

**Comment by yakutovicha** [comment]
> I've managed to fix the docs build in the end (in an ugly way). LMK if you want me to split it to a separate PR.


Since fixing Sphinx problems requires adding many dependencies, why don't we switch to a later version of Sphinx itself? Are there any issues with such an update??

**Comment by yakutovicha** [comment]
Also, the latest CI test failed because we are still on Python 3.8. Time to go on with Python>3.9?

**Comment by unkcpz** [comment]
> Time to go on with Python>3.9?

I think so, we drop it in AWB https://github.com/aiidalab/aiidalab-widgets-base/pull/557

**Comment by danielhollas** [comment]
Sorry for not being clear, I explain the reason why we can't simply update in a note in `setup.cfg`
https://github.com/aiidalab/aiidalab/pull/402/files#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R64

IMO the workaround is okay for now, but of course we need to fix it eventually.

> Also, the latest CI test failed because we are still supporting Python 3.8. Time to go on with Python>3.9?

This PR has already more stuff than I planned so I'll leave that to the next PR.
For now I simply put pre-commit v3.5 which is still compatible with Python 3.8.

**Comment by yakutovicha** [comment]
> > Since fixing Sphinx problems requires adding many dependencies, why don't we switch to a later version of Sphinx itself? Are there any issues with such an update??
> 
> Sorry for not being clear, I explain the reason why we can't simply update in a note in `setup.cfg` https://github.com/aiidalab/aiidalab/pull/402/files#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R64
> 
> Note that we're not adding new dependencies, we're pinning transitive dependencies that were already there. IMO the workaround is okay for now, but of course we need to fix it eventually.
> 
> > Also, the latest CI test failed because we are still supporting Python 3.8. Time to go on with Python>3.9?
> 
> This PR has already more stuff than I planned so I'll leave that to the next PR. For now I simply put pre-commit v3.5 which is still compatible with Python 3.8.

Thanks for explaining @danielhollas, makes sense to me.

**Pull request merged**
