### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by yakutovicha**
Unblock the second digit of the dependencies with semantic versioning
making it possible to do minor dependency updates without developers
intervention.

### CODE REVIEW

**Review by ltalirz — APPROVED** [review]
I see that you added some dependencies (click-spinner, dacite).
I guess that's on purpose.

Looks good to me

**Comment by csadorf** [comment]
> I see that you added some dependencies (click-spinner, dacite). I guess that's on purpose.
> 
> Looks good to me

I don't see any added dependencies. ❓

**Comment by ltalirz** [comment]
Right, I don't know what I saw there

**Comment by csadorf** [comment]
@ltalirz Do you want me to create a release so that https://github.com/aiidalab/aiidalab-widgets-base/pull/297 can pass?

**Comment by csadorf** [comment]
> please do!

@ltalirz @yakutovicha Done! 

https://github.com/aiidalab/aiidalab/releases/tag/v22.06.0

**Pull request merged**
