### PR TITLE
Determine remote branch from release line instead of checked out branch.

### PR DESCRIPTION
**Pull request by csadorf**
Makes installation flow robust against detached HEAD states.

### CODE REVIEW

**Review by yakutovicha — COMMENTED** [review]
Alright, so two things I discovered:

1. The apps without a remote repo get green "Latest version" instead of the red "Unable to determine.."
2. If the app was in "Detached state", it always remains there, even after the update.

Technically, though, things work just fine.

**Comment by csadorf** [comment]
I'll have a look at it. I'll need to investigate the failing test anyways. 

Just to confirm, would you prefer unregistered apps to always warn then?

**Comment by yakutovicha** [comment]
> Just to confirm, would you prefer unregistered apps to always warn then?

The best would be to show the yellow text "Unregistered app". Otherwise, to be honest, both are fine with me: "Latest version" is kind of also true, because it is indeed the latest available version; the long scary message about "Inability to determine the updates" is fine as well. Do you have an opinion on this?

**Comment by csadorf** [comment]
> > Just to confirm, would you prefer unregistered apps to always warn then?
> 
> The best would be to show the yellow text "Unregistered app". Otherwise, to be honest, both are fine with me: "Latest version" is kind of also true, because it is indeed the latest available version; the long scary message about "Inability to determine the updates" is fine as well. Do you have an opinion on this?

Since unregistered apps are considered development mode at the moment, I don't think it matters too much. Let's see how difficult it would be to display "Unregistered app", otherwise, I would suggest we leave it _as is_ and create an issue.

**Comment by csadorf** [comment]
@yakutovicha I've fixed the issue pertaining to the failing test and cleaned up the function implementation a little bit. I am going to address "recovering" from a detached HEAD state in a separate PR.

**Review by yakutovicha — APPROVED** [review]

**Pull request merged**
