### PR TITLE
Docs: How to develop an app

### LINKED ISSUE #154: AiiDAlab applications: How to develop an app.
A how-to guide that guides through the steps of building a small but functional application.

Maybe something like a QE band structure app would be a good example.

### PR DESCRIPTION
**Pull request by CasperWA**
Closes #154.

Extends upon the current documentation on "How to develop an AiiDAlab app".

### CODE REVIEW

**Comment by csadorf** [comment]
@CasperWA Can you fix the section headers, please? The first header level here should be the "chapter level": "* with overline for chapters"

**Comment by CasperWA** [comment]
> @CasperWA Can you fix the section headers, please? The first header level here should be the "chapter level": "* with overline for chapters"

Better now?

**Comment by csadorf** [comment]
> > @CasperWA Can you fix the section headers, please? The first header level here should be the "chapter level": "* with overline for chapters"
> 
> Better now?

Yes, perfect, thanks!

**Review by yakutovicha — APPROVED** [review]
very nice work, thanks a lot @CasperWA!

**Pull request merged**
